spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: root
  liquibase:
    change-log: db/changelog/main-changelog.xml